services:
  localstack:
    container_name: kiss_sqs_localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"   # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s 
