name: kiss_amazon_sqs_queue
description: Amazon SQS implementation for the kiss_queue interface
version: 0.1.0
repository: https://github.com/WAMF/kiss_amazon_sqs_queue

environment:
  sdk: ^3.8.0

dependencies:
  kiss_queue: ^0.2.1
  aws_sqs_api: ^2.0.0
  uuid: ^4.0.0
  very_good_analysis: ^9.0.0

dev_dependencies:
  kiss_queue_tests: ^0.1.2
  lints: ^5.0.0
  test: ^1.24.0
